quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.db-version=5.5.5

#=====PROD=====#
%prod.quarkus.http.port=5000
%prod.quarkus.datasource.username=root
%prod.quarkus.datasource.password=
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://mariadb:3306/test

#=====DEV=====#
%dev.quarkus.http.port=5001
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/test

#=====TEST=====#
%test.quarkus.http.port=5001
%test.quarkus.datasource.username=root
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/test
%test.quarkus.datasource.devservices.enabled=false