quarkus.hibernate-orm.schema-management.strategy=drop

quarkus.rest-client.lyrics.url=https://lrclib.net/api/
quarkus.rest-client.lyrics.connect-timeout=5000
quarkus.ssl.native=true
quarkus.tls.trust-all=true

#=====PROD=====#
%prod.quarkus.http.port=5000

#=====DEV=====#
%dev.quarkus.http.port=5001
%dev.quarkus.rest-client.logging.scope=request-response
%dev.quarkus.rest-client.logging.body-limit=5000
%dev.quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

#=====TEST=====#
%test.quarkus.http.port=5001