quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.db-version=8.0.0

#=====PROD=====#
%prod.quarkus.http.port=5000
%prod.quarkus.datasource.username=root
%prod.quarkus.datasource.password=
%prod.quarkus.datasource.jdbc.url=jdbc:mariadb://mariadb:3306/test

#=====DEV=====#
%dev.quarkus.http.port=5001
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3307/test

#=====TEST=====#
%test.quarkus.http.port=5001
%test.quarkus.datasource.username=root
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3307/test